# 开发环境配置文件

server:
  port: 8088
  max-http-header-size: 10240

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    druid:
      driver-class-name:  com.mysql.cj.jdbc.Driver
      #url: jdbc:mysql://82.157.246.141:3306/cos_db?serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&characterEncoding=UTF-8     # 数据库链接
      url: jdbc:mysql://127.0.0.1:3306/aggressivity_db?serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&characterEncoding=UTF-8     # 数据库链接
      #username: cos_db
      username: root
      #password: XPrayCTr6nBkaAFz
      password: root

  redis:
    # 地址
    host: 192.168.1.129
    # 端口，默认为6379
    port: 6379
    # 连接超时时间
    timeout: 10s
    trainjob-queue:
      key: train-queue
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制



